FPK_NAME = ncdu
FPK_VERS = 1.22
FPK_REV = 1

DEPENDS = cross/ncdu

MAINTAINER = yeled
DESCRIPTION = Disk usage analyzer with an ncurses interface.
STARTABLE = false

HOMEPAGE = https://dev.yorhel.nl/ncdu
LICENSE = MIT

SPK_COMMANDS = bin/ncdu

include ../../mk/fpksrc.fpk.mk
