FPK_NAME = pixz
FPK_VERS = 1.0.7
FPK_REV = 1

DEPENDS = cross/pixz

MAINTAINER = dotysan
DESCRIPTION = Parallel, indexed xz compressor.
DISPLAY_NAME = pixz

STARTABLE = false

HOMEPAGE = https://github.com/vasi/pixz
LICENSE = 2-Clause BSD

FPK_COMMANDS = bin/pixz

include ../../mk/fpksrc.fpk.mk
