FPK_NAME = procs
FPK_VERS = 0.14.10
FPK_REV = 1

DEPENDS = cross/procs

UNSUPPORTED_ARCHS = $(OLD_PPC_ARCHS)

MAINTAINER = FnOScommunity
DESCRIPTION = A modern replacement for ps written in Rust.
STARTABLE = false

HOMEPAGE = https://github.com/dalance/procs#readme
LICENSE  = MIT

SPK_COMMANDS = bin/procs

include ../../mk/fpksrc.fpk.mk
