FPK_NAME = mtr
FPK_VERS = 0.96
FPK_REV = 1

DEPENDS = cross/mtr

MAINTAINER = FnOScommunity
DESCRIPTION = mtr \(My traceroute\) combines the functionality of the 'traceroute' and 'ping' programs in a single network diagnostic tool.
DISPLAY_NAME = My traceroute
STARTABLE = false

HOMEPAGE = https://www.bitwizard.nl/mtr/
LICENSE  = GPLv2

FPK_COMMANDS = sbin/mtr sbin/mtr-packet

include ../../mk/fpksrc.fpk.mk
