FPK_NAME = strace
FPK_VERS = 6.9
SPK_REV = 1

DEPENDS = cross/strace

MAINTAINER = FnOScommunity
DESCRIPTION = strace is a diagnostic, debugging and instructional userspace utility for Linux.
DISPLAY_NAME = strace
STARTABLE = false

HOMEPAGE = https://strace.io/
LICENSE = GPLv2+

SPK_COMMANDS = bin/strace bin/strace-log-merge

include ../../mk/fpksrc.fpk.mk
