FPK_NAME = micro
SPK_VERS = 2.0.14
SPK_REV = 1
SPK_ICON = src/micro.png

DEPENDS = cross/micro

MAINTAINER = FnOScommunity
DESCRIPTION = A modern and intuitive terminal-based text editor.
DISPLAY_NAME = micro
STARTABLE = false

HOMEPAGE = https://micro-editor.github.io/
LICENSE  = MIT

SPK_COMMANDS = bin/micro

include ../../mk/fpksrc.fpk.mk
