FPK_NAME = screen
FPK_VERS = 4.9.1
FPK_REV = 1

DEPENDS = cross/screen

MAINTAINER = FnOScommunity
DESCRIPTION = Screen is a full-screen window manager that multiplexes a physical terminal between several processes, typically interactive shells.
DISPLAY_NAME = screen
STARTABLE = false

HOMEPAGE = https://www.gnu.org/software/screen/
LICENSE = GPLv2

FPK_COMMANDS = bin/screen

include ../../mk/fpksrc.fpk.mk
