FPK_NAME = expect
FPK_VERS = 5.45.4
SPK_REV = 1

DEPENDS = cross/expect

MAINTAINER = FnOScommunity
DESCRIPTION = Expect is a tool for automating interactive applications such as telnet, ftp, passwd, fsck, rlogin, tip, etc. Expect is also useful for testing these same applications.
STARTABLE = false

HOMEPAGE = https://www.nist.gov/services-resources/software/expect
LICENSE  = Public Domain

SPK_COMMANDS = bin/expect

include ../../mk/fpksrc.fpk.mk
