FPK_NAME = curaengine
FPK_VERS = 2.1.3
FPK_REV = 2
FPK_ICON = src/curaengine.png

DEPENDS = cross/curaengine

# c++11 compiler required
UNSUPPORTED_ARCHS = $(OLD_PPC_ARCHS) $(ARMv5_ARCHS)

MAINTAINER = FnOScommunity
DESCRIPTION  = CuraEngine is a powerful, fast and robust engine for processing 3D models into 3D printing instruction for Ultimaker and other GCode based 3D printers.
DISPLAY_NAME = CuraEngine

HOMEPAGE = https://ultimaker.com/software/ultimaker-cura
LICENSE  = AGPLv3

STARTABLE = false
FPK_COMMANDS = bin/CuraEngine

include ../../mk/fpksrc.fpk.mk
