FPK_NAME = iperf2
FPK_VERS = 2.2.1
FPK_REV = 1
SPK_ICON = src/iperf2.png

DEPENDS = cross/iperf2

MAINTAINER = hgy59
DESCRIPTION = A tool for measuring TCP and UDP network performance, based on iperf 2.0.5.
DISPLAY_NAME = iperf2
STARTABLE = false

HOMEPAGE = https://sourceforge.net/projects/iperf2/
LICENSE = BSD

SPK_COMMANDS = bin/iperf2

include ../../mk/fpksrc.fpk.mk
