SPK_NAME = fossil-scm
SPK_VERS = 2.17
SPK_REV = 3
SPK_ICON = src/fossil-scm.png

DEPENDS = cross/fossil-scm

MAINTAINER = FnOScommunity
DISPLAY_NAME = Fossil SCM

DESCRIPTION = "Fossil is a simple, high-reliability, distributed software configuration management system."
STARTABLE = false
CHANGELOG = "1. Update fossil-scm to 2.17.<br/>2. Update openssl to 1.1.1l."

HOMEPAGE = https://www.fossil-scm.org/
LICENSE  = 2-clause BSD

SPK_COMMANDS = bin/fossil

include ../../mk/fpksrc.fpk.mk
