FPK_NAME = sshfs2
FPK_VERS = 2.10
FPK_REV = 1

DEPENDS = cross/sshfs2

MAINTAINER = FnOScommunity
DESCRIPTION = sshfs is a network filesystem client to connect to SSH servers.
DISPLAY_NAME = sshfs
STARTABLE = false

HOMEPAGE = https://github.com/libfuse/sshfs
LICENSE = GPLv2

SPK_COMMANDS = bin/sshfs

include ../../mk/fpksrc.fpk.mk
