FPK_NAME = less
FPK_VERS = 685
FPK_REV = 1
FPK_ICON = src/gnu-logo.png

DEPENDS = cross/less

MAINTAINER = FnOScommunity
DESCRIPTION = Less is a terminal pager.
DISPLAY_NAME = Less
STARTABLE = false

HOMEPAGE = https://www.gnu.org/software/less/
LICENSE = GPLv3

SPK_COMMANDS = bin/less bin/lessecho bin/lesskey

include ../../mk/fpksrc.fpk.mk
