FPK_NAME = binutils
FPK_VERS = 2.42
FPK_REV = 1

DEPENDS = cross/binutils

MAINTAINER = FnOScommunity
DESCRIPTION = GNU Binutils.
STARTABLE = false

HOMEPAGE = https://www.gnu.org/software/binutils/
LICENSE = GPLv2/LGPLv2

FPK_COMMANDS  = bin/addr2line
FPK_COMMANDS += bin/ar
FPK_COMMANDS += bin/as
FPK_COMMANDS += bin/c++filt
FPK_COMMANDS += bin/dwp
FPK_COMMANDS += bin/elfedit
FPK_COMMANDS += bin/embedspu
FPK_COMMANDS += bin/gp-archive
FPK_COMMANDS += bin/gp-collect-app
FPK_COMMANDS += bin/gp-display-html
FPK_COMMANDS += bin/gp-display-src
FPK_COMMANDS += bin/gp-display-text
FPK_COMMANDS += bin/gprof
FPK_COMMANDS += bin/gprofng
FPK_COMMANDS += bin/ld
FPK_COMMANDS += bin/ld.bfd
FPK_COMMANDS += bin/ld.gold
FPK_COMMANDS += bin/nm
FPK_COMMANDS += bin/objcopy
FPK_COMMANDS += bin/objdump
FPK_COMMANDS += bin/ranlib
FPK_COMMANDS += bin/readelf
FPK_COMMANDS += bin/size
FPK_COMMANDS += bin/strings
FPK_COMMANDS += bin/strip

include ../../mk/fpksrc.fpk.mk
