FPK_NAME = autoconf
FPK_VERS = 2.72
FPK_REV = 1

DEPENDS = cross/autoconf

MAINTAINER = FnOScommunity
DESCRIPTION = Autoconf is an extensible package of M4 macros that produce shell scripts to automatically configure software source code packages.
LICENSE  = GPLv2
DISPLAY_NAME = autoconf
STARTABLE = false

HOMEPAGE = https://www.gnu.org/software/autoconf/

FPK_COMMANDS  = bin/autoconf
FPK_COMMANDS += bin/autoheader
FPK_COMMANDS += bin/autom4te
FPK_COMMANDS += bin/autoreconf
FPK_COMMANDS += bin/autoscan
FPK_COMMANDS += bin/autoupdate
FPK_COMMANDS += bin/ifnames

include ../../mk/fpksrc.fpk.mk
