FPK_NAME = aria2
FPK_VERS = 1.37.0
SPK_REV = 1
SPK_ICON = src/aria2.png

DEPENDS = cross/aria2

MAINTAINER = cnrat
DESCRIPTION = aria2 is a lightweight multi-protocol and multi-source command-line download utility.
DESCRIPTION_CHS = Aria2是一个命令行下运行、多协议、多来源下载工具（HTTP/HTTPS、FTP、BitTorrent、Metalink）。
DISPLAY_NAME = Aria2

STARTABLE = false

LICENSE  = GPLv2/GPLv3
HOMEPAGE = http://aria2.github.io

SPK_COMMANDS = bin/aria2c

include ../../mk/fpksrc.fpk.mk
