FPK_NAME = gpart
FPK_VERS = 0.3
FPK_REV = 1

DEPENDS = cross/gpart

UNSUPPORTED_ARCHS = $(OLD_PPC_ARCHS)

MAINTAINER = FnOScommunity
DESCRIPTION = Gpart is a small tool which tries to guess what partitions are on a PC type, MBR-partitioned hard disk in case the primary partition table was damaged.
STARTABLE = false

HOMEPAGE = https://github.com/baruch/gpart
LICENSE = GPLv2

SPK_COMMANDS = sbin/gpart

include ../../mk/fpksrc.fpk.mk
