FPK_NAME = davfs2
SPK_VERS = 1.7.2
SPK_REV = 1
SPK_ICON = src/davfs2.png

DEPENDS = cross/davfs2

MAINTAINER = FnOScommunity
DESCRIPTION = Mount a WebDAV resource as a regular file system.
STARTABLE = false

HOMEPAGE = http://savannah.nongnu.org/projects/davfs2
LICENSE = GPLv3+

SPK_COMMANDS = sbin/mount.davfs sbin/umount.davfs

include ../../mk/fpksrc.fpk.mk
