FPK_NAME = dutree
FPK_VERS = 0.2.18
FPK_REV = 1

DEPENDS = cross/dutree

UNSUPPORTED_ARCHS = $(OLD_PPC_ARCHS)

MAINTAINER = FnOScommunity
DESCRIPTION = A tool to analyze file system usage written in Rust.
DISPLAY_NAME = $(FPK_NAME)
STARTABLE = false

HOMEPAGE = https://ownyourbits.com/2018/03/25/analyze-disk-usage-with-dutree/
LICENSE  = GPLv3

SPK_COMMANDS = bin/dutree

include ../../mk/fpksrc.fpk.mk
