FPK_NAME = pigz
FPK_VERS = 2.8
FPK_REV = 1

DEPENDS = cross/pigz

MAINTAINER = FnOScommunity
DESCRIPTION = A parallel implementation of gzip for modern multi-processor, multi-core machines.
DISPLAY_NAME = pigz
STARTABLE = false

HOMEPAGE = https://zlib.net/pigz/
LICENSE = zlib

FPK_COMMANDS = bin/pigz bin/unpigz

include ../../mk/fpksrc.fpk.mk
