FPK_NAME = socat
FPK_VERS = 1.8.0.3
FPK_REV = 1

DEPENDS = cross/socat

MAINTAINER = FnOScommunity
DESCRIPTION = socat - Multipurpose relay \(SOcket CAT)\. Socat is a command line based utility that establishes two bidirectional byte streams and transfers data between them. Because the streams can be constructed from a large set of different types of data sinks and sources, and because lots of address options may be applied to the streams, socat can be used for many different purposes.

DISPLAY_NAME = socat
STARTABLE = false

HOMEPAGE = http://www.dest-unreach.org/socat/
LICENSE = GPLv2

FPK_COMMANDS = bin/socat bin/socat1 bin/filan bin/procan
FPK_COMMANDS += bin/socat-broker.sh bin/socat-chain.sh bin/socat-mux.sh

include ../../mk/fpksrc.fpk.mk
