FPK_NAME = js
FPK_VERS = 1.6.20070208
FPK_REV = 1

DEPENDS = cross/js

MAINTAINER = FnOScommunity
DESCRIPTION = Mozilla JavaScript Engine
RELOAD_UI = no
DISPLAY_NAME = OSSP JavaScript
STARTABLE = false
CHANGELOG = Initial release

HOMEPAGE = http://www.ossp.org/pkg/lib/js/
LICENSE = MPL/GPL/LGPL tri-license

FPK_COMMANDS = "bin/js bin/jslint bin/jspack"

include ../../mk/fpksrc.fpk.mk
