FPK_NAME = duf
FPK_VERS = 0.9.1
SPK_REV = 1

DEPENDS = cross/duf

UNSUPPORTED_ARCHS = $(PPC_ARCHS)

MAINTAINER = FnOScommunity
DESCRIPTION = Disk Usage/Free Utility - a better 'df' alternative.
STARTABLE = false

HOMEPAGE = https://github.com/muesli/duf
LICENSE  = MIT

SPK_COMMANDS = bin/duf

include ../../mk/fpksrc.fpk.mk
