FPK_NAME = jpegoptim
FPK_VERS = 1.4.6
SPK_REV = 1

DEPENDS = cross/jpegoptim

MAINTAINER = FnOScommunity
DESCRIPTION = utility to optimize/compress JPEG files 
DISPLAY_NAME = jpegoptim
STARTABLE = false

HOMEPAGE = https://github.com/tjko/jpegoptim
LICENSE  = GPLv2

HELP_URL = https://www.kokkonen.net/tjko/src/man/jpegoptim.txt

SPK_COMMANDS = bin/jpegoptim

include ../../mk/fpksrc.fpk.mk
