SPK_NAME = etherwake
SPK_VERS = 1.09
SPK_REV = 1

DEPENDS = cross/etherwake

MAINTAINER = FnOScommunity
DESCRIPTION = Generate and transmit a Wake-On-LAN (WOL) Magic Packet
DISPLAY_NAME = etherwake
STARTABLE = false

# homepage is not reachable anymore
HOMEPAGE = www.scyld.com/wakeonlan.html
LICENSE  = GPL

SPK_COMMANDS = bin/etherwake

include ../../mk/fpksrc.fpk.mk
