FPK_NAME = alsa-utils
FPK_VERS = 1.2.9
FPK_REV = 1

DEPENDS = cross/alsa-utils

UNSUPPORTED_ARCHS = $(OLD_PPC_ARCHS)

MAINTAINER = FnOScommunity
DESCRIPTION = Advanced Linux Sound Architecture provides audio and MIDI functionality to the Linux operating system.
STARTABLE = false

HOMEPAGE = https://www.alsa-project.org/
LICENSE = GPLv2

FPK_COMMANDS  = bin/aconnect
FPK_COMMANDS += bin/alsabat
FPK_COMMANDS += bin/alsaloop
FPK_COMMANDS += bin/alsamixer
FPK_COMMANDS += bin/alsatplg
FPK_COMMANDS += bin/alsaucm
FPK_COMMANDS += bin/amidi
FPK_COMMANDS += bin/amixer
FPK_COMMANDS += bin/aplay
FPK_COMMANDS += bin/aplaymidi
FPK_COMMANDS += bin/arecord
FPK_COMMANDS += bin/arecordmidi
FPK_COMMANDS += bin/aseqdump
FPK_COMMANDS += bin/aseqnet
FPK_COMMANDS += bin/axfer
FPK_COMMANDS += bin/iecset
FPK_COMMANDS += bin/speaker-test

include ../../mk/fpksrc.fpk.mk
