FPK_NAME = fzf
FPK_VERS = 0.67.0
FPK_REV = 1
FPK_ICON = src/fzf.png

UNSUPPORTED_ARCHS = $(PPC_ARCHS)

DEPENDS = cross/fzf

MAINTAINER = FnOScommunity
DESCRIPTION = A command-line fuzzy finder.
STARTABLE = false

HOMEPAGE = https://junegunn.github.io/fzf/
LICENSE = MIT

FPK_COMMANDS = bin/fzf

include ../../mk/fpksrc.fpk.mk
