FPK_NAME = jdupes
FPK_VERS = 1.30.0
FPK_REV = 1
FPK_ICON = src/jdupes.png

DEPENDS = cross/jdupes

MAINTAINER = jbruchon
DESCRIPTION = A powerful duplicate file finder and an enhanced fork of fdupes.
STARTABLE = false

HOMEPAGE = https://github.com/jbruchon/jdupes/
LICENSE = MIT

SPK_COMMANDS = bin/jdupes

include ../../mk/fpksrc.fpk.mk
