PKG_NAME = intel-mediasdk-main

OPTIONAL_DEPENDS  = cross/intel-mediasdk-latest
OPTIONAL_DEPENDS += cross/intel-mediasdk-22.5

include ../../mk/fpksrc.main-depends.mk

DEPENDS = cross/intel-mediasdk-latest
