FPK_NAME = libtree
FPK_VERS = 3.1.1
FPK_REV = 1

DEPENDS = cross/libtree

MAINTAINER = FnOScommunity
DESCRIPTION = A tool that turns ldd into a tree and explains how shared libraries are found or why they cannot be located.
DISPLAY_NAME = libtree
STARTABLE = false

HOMEPAGE = https://github.com/haampie/libtree
LICENSE = MIT

SPK_COMMANDS = bin/libtree

include ../../mk/fpksrc.fpk.mk
