PKG_NAME = intel-media-main

OPTIONAL_DEPENDS  = cross/intel-media-driver-latest
OPTIONAL_DEPENDS += cross/intel-media-driver-22.5

include ../../mk/fpksrc.main-depends.mk

DEPENDS = cross/intel-media-driver-latest
