SPK_NAME = stunnel
SPK_VERS = 5.60
SPK_REV = 2
SPK_ICON = src/stunnel.png

DEPENDS = cross/stunnel

BETA = 1

MAINTAINER = hgy59
DESCRIPTION = "Stunnel is a proxy designed to add TLS encryption functionality to existing clients and servers without any changes in the programs\' code."
DISPLAY_NAME = stunnel TLS Proxy
STARTABLE = false
CHANGELOG = "1. Update stunnel to v5.60<br/>2. Update OpenSSL to v1.1.1l<br/><br/>This is an experimental release. Please provide issues and package improvements at <a href="https://github.com/fnoscommunity/fpksrc/issues">FnOScommunity</a>"

HOMEPAGE = https://www.stunnel.org/
LICENSE  = GPLv2+

SERVICE_USER = auto

SPK_COMMANDS = bin/stunnel bin/stunnel3

include ../../mk/fpksrc.fpk.mk
