FPK_NAME = lua
FPK_VERS = 5.4.8
FPK_REV = 6
FPK_ICON = src/lua.png

DEPENDS = cross/lua

MAINTAINER = eelcohn
MAINTAINER_URL = https://www.lua.org/
HELPURL = https://www.lua.org/start.html

DESCRIPTION = Lua is a powerful, efficient, lightweight, embeddable scripting language. It supports procedural programming, object-oriented programming, functional programming, data-driven programming, and data description.
DISPLAY_NAME = Lua
STARTABLE = false
CHANGELOG = "Update lua to v5.4.8"

HOMEPAGE = https://www.lua.org
LICENSE = MIT

FPK_COMMANDS = bin/lua bin/luac

include ../../mk/fpksrc.fpk.mk
