FPK_NAME = uhubctl
SPK_VERS = 2.5.0
SPK_REV = 1

DEPENDS = cross/uhubctl

MAINTAINER = FnOScommunity
DESCRIPTION = USB hub per-port power control.
STARTABLE = false

HOMEPAGE = https://github.com/mvp/uhubctl
LICENSE  = GPLv2

SPK_COMMANDS = bin/uhubctl

include ../../mk/fpksrc.fpk.mk
