FPK_NAME = uhubctl
FPK_VERS = 2.5.0
FPK_REV = 1

DEPENDS = cross/uhubctl

MAINTAINER = FnOScommunity
DESCRIPTION = USB hub per-port power control.
STARTABLE = false

HOMEPAGE = https://github.com/mvp/uhubctl
LICENSE  = GPLv2

FPK_COMMANDS = bin/uhubctl

include ../../mk/fpksrc.fpk.mk
