FPK_NAME = lzip
FPK_VERS = 1.25
FPK_REV = 1
FPK_ICON = src/lzip.png

DEPENDS = cross/lzip cross/plzip

MAINTAINER = FnOScommunity
DESCRIPTION = Lzip is a lossless data compressor with a user interface similar to the one of gzip or bzip2. Lzip uses a simplified form of the 'Lempel-Ziv-Markov chain-Algorithm' (LZMA) stream format, chosen to maximize safety and interoperability.
DESCRIPTION += <br/>Plzip is a massively parallel (multi-threaded) implementation of lzip, fully compatible with lzip 1.4 or newer.
DISPLAY_NAME = Lzip
STARTABLE = false

HOMEPAGE = http://lzip.nongnu.org/plzip.html
LICENSE = GPLv2

FPK_COMMANDS = bin/lzip bin/plzip

include ../../mk/fpksrc.fpk.mk
