FPK_NAME = bandwhich
FPK_VERS = 0.23.1
FPK_REV = 1

DEPENDS = cross/bandwhich

# unknown relocation type 95 ...
UNSUPPORTED_ARCHS = $(OLD_PPC_ARCHS)

MAINTAINER = FnOScommunity
DESCRIPTION = CLI utility for displaying current network utilization by process, connection and remote IP/hostname.
STARTABLE = false

HOMEPAGE = https://github.com/imsnif/bandwhich#readme
LICENSE  = MIT

SPK_COMMANDS = bin/bandwhich

include ../../mk/fpksrc.fpk.mk
