FPK_NAME = mg
FPK_VERS = 3.7
SPK_REV = 1
SPK_ICON = src/unix.png

DEPENDS = cross/mg

MAINTAINER = FnOScommunity
DESCRIPTION = Micro \(GNU\) Emacs-like text editor.

DISPLAY_NAME = "mg (micro gnu)"
STARTABLE = false

HOMEPAGE = https://man.troglobit.com/man1/mg.1.html
LICENSE  = UNLICENSE

SPK_COMMANDS = bin/mg

include ../../mk/fpksrc.fpk.mk
