FPK_NAME = nmon
FPK_VERS = 16s
FPK_REV = 1
FPK_ICON = src/nmon.png

DEPENDS = cross/nmon

MAINTAINER = biyiklioglu
DESCRIPTION = nmon \(Nigel\'s performance Monitor\) is a performance monitoring tool for Linux
DISPLAY_NAME = nmon
STARTABLE = false

HOMEPAGE = http://nmon.sourceforge.net/
LICENSE = GPLv3
HELP_URL = http://nmon.sourceforge.net/pmwiki.php

SPK_COMMANDS = bin/nmon

include ../../mk/fpksrc.fpk.mk
