SPK_NAME = ionice
SPK_VERS = 2.41.2
SPK_REV = 1

DEPENDS = cross/ionice

MAINTAINER = FnOScommunity
DESCRIPTION = ionice of util-linux (random collection of Linux utilities).
STARTABLE = false

HOMEPAGE = https://github.com/util-linux/util-linux
LICENSE  = GPLv2

SPK_COMMANDS = bin/ionice

include ../../mk/fpksrc.fpk.mk
