FPK_NAME = ionice
FPK_VERS = 2.41.2
FPK_REV = 1

DEPENDS = cross/ionice

MAINTAINER = FnOScommunity
DESCRIPTION = ionice of util-linux (random collection of Linux utilities).
STARTABLE = false

HOMEPAGE = https://github.com/util-linux/util-linux
LICENSE  = GPLv2

FPK_COMMANDS = bin/ionice

include ../../mk/fpksrc.fpk.mk
