FPK_NAME = dos2unix
FPK_VERS = 7.5.3
FPK_REV = 1

DEPENDS = cross/dos2unix

MAINTAINER = FnOScommunity
DESCRIPTION = Convert text files with DOS or Mac line breaks to Unix line breaks and vice versa.
STARTABLE = false

HOMEPAGE = https://waterlan.home.xs4all.nl/dos2unix.html
LICENSE = FreeBSD style

FPK_COMMANDS = bin/dos2unix bin/unix2dos bin/mac2unix bin/unix2mac 

include ../../mk/fpksrc.fpk.mk
