FPK_NAME = gdu
FPK_VERS = 5.31.0
SPK_REV = 1

DEPENDS = cross/gdu

UNSUPPORTED_ARCHS = $(PPC_ARCHS)

MAINTAINER = FnOScommunity
DESCRIPTION = Fast disk usage analyzer with console interface written in Go.
STARTABLE = false

HOMEPAGE = https://github.com/dundee/gdu
LICENSE  = MIT

SPK_COMMANDS = bin/gdu

include ../../mk/fpksrc.fpk.mk
