FPK_NAME = net-snmp
FPK_VERS = 5.9.4
FPK_REV = 1

DEPENDS = cross/net-snmp

MAINTAINER = FnOScommunity
DESCRIPTION = Net-SNMP is a suite of applications used to implement SNMP v1, SNMP v2c and SNMP v3 using both IPv4 and IPv6.
DISPLAY_NAME = Net-SNMP
STARTABLE = false

HOMEPAGE = http://www.net-snmp.org/
LICENSE = BSD and CMU/UCD (BSD like)

FPK_COMMANDS  = bin/snmpbulkget
FPK_COMMANDS += bin/snmpbulkwalk
FPK_COMMANDS += bin/snmpdelta
FPK_COMMANDS += bin/snmpdf
FPK_COMMANDS += bin/snmpget
FPK_COMMANDS += bin/snmpgetnext
FPK_COMMANDS += bin/snmpinform
FPK_COMMANDS += bin/snmpnetstat
FPK_COMMANDS += bin/snmpping
FPK_COMMANDS += bin/snmpps
FPK_COMMANDS += bin/snmpset
FPK_COMMANDS += bin/snmpstatus
FPK_COMMANDS += bin/snmptable
FPK_COMMANDS += bin/snmptest
FPK_COMMANDS += bin/snmptranslate
FPK_COMMANDS += bin/snmptrap
FPK_COMMANDS += bin/snmpusm
FPK_COMMANDS += bin/snmpvacm
FPK_COMMANDS += bin/snmpwalk

include ../../mk/fpksrc.fpk.mk
