FPK_NAME = zstd
FPK_VERS = 1.5.7
FPK_REV = 1
FPK_ICON = src/zstd.png

DEPENDS = cross/zstd

MAINTAINER = FnOScommunity
DESCRIPTION = Zstandard is a fast compression algorithm, providing high compression ratios.
DISPLAY_NAME = Zstandard
STARTABLE = false

HOMEPAGE = https://facebook.github.io/zstd/
LICENSE  = GPLv2/BSD

SPK_COMMANDS = bin/zstd bin/unzstd bin/zstdcat bin/zstdmt bin/zstdgrep bin/zstdless bin/zstd-frugal

include ../../mk/fpksrc.fpk.mk
