FPK_NAME = gnupg
FPK_VERS = 2.4.8
FPK_REV = 7
FPK_ICON = src/gnupg.png

DEPENDS = cross/gnupg

MAINTAINER = FnOScommunity
DESCRIPTION = GnuPG allows to encrypt and sign your data and communication, features a versatile key management system as well as access modules for all kinds of public key directories.
STARTABLE = false
DISPLAY_NAME = GnuPG
CHANGELOG = "1. Update gnupg to 2.4.8<br/>2. Update shared libraries."

HOMEPAGE = https://www.gnupg.org/
LICENSE  = GPLv3

FPK_COMMANDS = bin/gpg
FPK_COMMANDS += bin/gpg-agent
FPK_COMMANDS += bin/gpg-card
FPK_COMMANDS += bin/gpg-connect-agent
FPK_COMMANDS += bin/gpgconf
FPK_COMMANDS += bin/gpgsm
FPK_COMMANDS += bin/gpgscm
FPK_COMMANDS += bin/gpgtar
FPK_COMMANDS += bin/gpgsplit
FPK_COMMANDS += bin/gpgparsemail
FPK_COMMANDS += bin/gpgv
FPK_COMMANDS += bin/gpg-error
FPK_COMMANDS += bin/gpg-wks-client
FPK_COMMANDS += bin/gpg-wks-server
FPK_COMMANDS += bin/kbxutil
FPK_COMMANDS += bin/watchgnupg

include ../../mk/fpksrc.fpk.mk
