FPK_NAME = cpulimit
FPK_VERS = 0.2
FPK_REV = 1

DEPENDS = cross/cpulimit

MAINTAINER = FnOScommunity
DESCRIPTION = CPU usage limiter for Linux.
STARTABLE = false

HOMEPAGE = https://github.com/opsengine/cpulimit
LICENSE  = GPLv2+

FPK_COMMANDS = bin/cpulimit

include ../../mk/fpksrc.fpk.mk
