FPK_NAME = cpulimit
SPK_VERS = 0.2
SPK_REV = 1

DEPENDS = cross/cpulimit

MAINTAINER = FnOScommunity
DESCRIPTION = CPU usage limiter for Linux.
STARTABLE = false

HOMEPAGE = https://github.com/opsengine/cpulimit
LICENSE  = GPLv2+

SPK_COMMANDS = bin/cpulimit

include ../../mk/fpksrc.fpk.mk
