FPK_NAME = fdupes
FPK_VERS = 2.4.0
FPK_REV = 1
FPK_ICON = src/fdupes.png

DEPENDS = cross/fdupes

MAINTAINER = biyiklioglu
DESCRIPTION = FDUPES is a program for identifying or deleting duplicate files residing within specified directories.
DISPLAY_NAME = FDUPES
STARTABLE = false

HOMEPAGE = https://github.com/adrianlopezroche/fdupes/
LICENSE = MIT
HELP_URL = https://github.com/adrianlopezroche/fdupes/wiki

FPK_COMMANDS = bin/fdupes

include ../../mk/fpksrc.fpk.mk
