FPK_NAME = nano
FPK_VERS = 8.7
FPK_REV = 1
FPK_ICON = src/nano.png

DEPENDS = cross/nano

MAINTAINER = FnOScommunity
DESCRIPTION = nano is a text editor for Unix-like computing systems or operating environments using a command line interface.
DESCRIPTION_GER = nano ist ein einfacher Editor, der die Bearbeitung von Dateien in einem Terminal bzw. auf der Konsole erlaubt.
STARTABLE = false

HOMEPAGE = https://www.nano-editor.org
LICENSE = GPLv2

SERVICE_SETUP = src/service-setup.sh

FPK_COMMANDS = bin/nano bin/rnano

include ../../mk/fpksrc.fpk.mk
