FPK_NAME = patch
FPK_VERS = 2.8
FPK_REV = 1

DEPENDS = cross/patch

MAINTAINER = FnOScommunity
DESCRIPTION = Patch takes a patch file containing a difference listing produced by the diff program and applies those differences to one or more original files, producing patched versions.
STARTABLE = false

HOMEPAGE = https://savannah.gnu.org/projects/patch/
LICENSE  = GPLv3+

SPK_COMMANDS = bin/patch

include ../../mk/fpksrc.fpk.mk
