FPK_NAME = disktype
FPK_VERS = 9
FPK_REV = 1

DEPENDS = cross/disktype

MAINTAINER = FnOScommunity
DESCRIPTION = Detects the content format of a disk or disk image by checking for signatures of file systems, partition tables, and boot codes.
STARTABLE = false

HOMEPAGE = https://disktype.sourceforge.net/
LICENSE = MIT

SPK_COMMANDS = bin/disktype

include ../../mk/fpksrc.fpk.mk
