FPK_NAME = links
FPK_VERS = 2.30
FPK_REV = 1
FPK_ICON = src/links.png

DEPENDS = cross/links

MAINTAINER = FnOScommunity
DESCRIPTION = Links is a web browser running in text mode.
DISPLAY_NAME = Links
STARTABLE = false

HOMEPAGE = http://links.twibright.com/
LICENSE = GPLv2

SPK_COMMANDS = bin/links

include ../../mk/fpksrc.fpk.mk
