SPK_NAME = sd
SPK_VERS = 1.0.0
SPK_REV = 1

DEPENDS = cross/sd

UNSUPPORTED_ARCHS = $(OLD_PPC_ARCHS)

MAINTAINER = FnOScommunity
DESCRIPTION = Intuitive find & replace CLI (sed alternative).
STARTABLE = no

HOMEPAGE = https://github.com/chmln/sd#readme
LICENSE  = MIT

SPK_COMMANDS = bin/sd

include ../../mk/fpksrc.fpk.mk
