FPK_NAME = sshfs3
FPK_VERS = 3.7.3
FPK_REV = 1

DEPENDS = cross/sshfs3

UNSUPPORTED_ARCHS = $(OLD_PPC_ARCHS)

MAINTAINER = FnOScommunity
DESCRIPTION = sshfs is a network filesystem client to connect to SSH servers.
DISPLAY_NAME = sshfs
STARTABLE = false

HOMEPAGE = https://github.com/libfuse/sshfs
LICENSE = GPLv2

FPK_COMMANDS = bin/sshfs

include ../../mk/fpksrc.fpk.mk
