FPK_NAME = inetutils
FPK_VERS = 2.6
FPK_REV = 1

DEPENDS = cross/inetutils

MAINTAINER = FnOScommunity
DESCRIPTION = GNU network utilities.
STARTABLE = false

HOMEPAGE = https://www.gnu.org/software/inetutils/
LICENSE = GPLv3

FPK_COMMANDS = bin/telnet bin/whois

include ../../mk/fpksrc.fpk.mk
