FPK_NAME = memaslap
FPK_VERS = 1.0
FPK_REV = 1

DEPENDS = cross/libmemcached

MAINTAINER = FnOScommunity
DESCRIPTION = memaslap is a load generation and benchmark tool for memcached servers. It generates configurable workload such as threads, concurrencies, connections, run time, overwrite, miss rate, key size, value size, get/set proportion, expected throughput, and so on.
STARTABLE = false

HOMEPAGE = http://docs.libmemcached.org/bin/memaslap.html
LICENSE = 3-Clause BSD

FPK_COMMANDS = bin/memaslap

include ../../mk/fpksrc.fpk.mk
