FPK_NAME = tdu
FPK_VERS = 1.36
FPK_REV = 1

DEPENDS = cross/tdu

UNSUPPORTED_ARCHS = $(PPC_ARCHS)

MAINTAINER = FnOScommunity
DESCRIPTION = Top Disk Usage. You want to know what is using all your disk space? This command-line tool estimates the disk space occupied by all files in a given path. It displays a sorted list of the biggest items. The estimation method is similar to the 'du -skx' command from GNU Coreutils package.
DISPLAY_NAME = $(FPK_NAME)
STARTABLE = false

HOMEPAGE = https://github.com/josephpaul0/tdu
LICENSE  = GPLv2

FPK_COMMANDS = bin/tdu

include ../../mk/fpksrc.fpk.mk
