SPK_NAME = bc
SPK_VERS = 1.06
SPK_REV = 1
SPK_ICON = src/gnu-logo.png

DEPENDS = cross/bc

MAINTAINER = FnOScommunity
DESCRIPTION = bc is an arbitrary precision numeric processing language.
DISPLAY_NAME = bc
STARTABLE = false

HOMEPAGE = https://www.gnu.org/software/bc/
LICENSE = GPLv3
HELP_URL = https://www.gnu.org/software/bc/manual/html_mono/bc.html

SPK_COMMANDS = bin/bc bin/dc

include ../../mk/fpksrc.fpk.mk
