FPK_NAME = helix
FPK_VERS = 25.07.1
FPK_REV = 1
FPK_ICON = src/helix.png

DEPENDS = cross/helix

UNSUPPORTED_ARCHS = $(ARMv5_ARCHS) $(PPC_ARCHS) $(ARMv7L_ARCHS)

MAINTAINER = FnOScommunity
DESCRIPTION = A post-modern modal text editor.
DISPLAY_NAME = helix
STARTABLE = false
CHANGELOG = "Initial package release"

HOMEPAGE = https://helix-editor.com/
LICENSE = MPL-2.0

SPK_COMMANDS = bin/hx

include ../../mk/fpksrc.fpk.mk
