FPK_NAME = fritzctl
FPK_VERS = 1.4.23
FPK_REV = 1
FPK_ICON = src/fritzctl.png

DEPENDS = cross/fritzctl

MAINTAINER = bpicode
DESCRIPTION = A lightweight, easy to use console client for the AVM FRITZ!Box Home Automation.
DISPLAY_NAME = fritzctl
STARTABLE = false
CHANGELOG = Initial release

HOMEPAGE = https://github.com/bpicode/fritzctl
LICENSE = MIT

SPK_COMMANDS = bin/fritzctl

UNSUPPORTED_ARCHS = $(PPC_ARCHS)

include ../../mk/fpksrc.fpk.mk
