FPK_NAME = netcat
FPK_VERS = 0.7.1
FPK_REV = 1

DEPENDS = cross/netcat

MAINTAINER = FnOScommunity
DESCRIPTION = Netcat is a featured networking utility which reads and writes data across network connections, using the TCP/IP protocol.
DISPLAY_NAME = netcat
STARTABLE = false

HOMEPAGE = https://netcat.sourceforge.net/
LICENSE = GPLv2

FPK_COMMANDS = bin/nc bin/netcat

include ../../mk/fpksrc.fpk.mk
