FPK_NAME = tree
FPK_VERS = 2.2.1
FPK_REV = 1

DEPENDS = cross/tree

MAINTAINER = MrSpoocy
DESCRIPTION = Tree is a recursive directory listing command that produces a depth indented listing of files, which is colorized ala dircolors if the LS_COLORS environment variable is set and output is to tty.
STARTABLE = false

HOMEPAGE = https://oldmanprogrammer.net/source.php?dir=projects/tree
LICENSE  = GPLv2

FPK_COMMANDS = bin/tree

include ../../mk/fpksrc.fpk.mk
