FPK_NAME = ghostscript
FPK_VERS = 10.05.0
FPK_REV = 1
FPK_ICON = src/ghostscript.png

DEPENDS = cross/ghostscript

UNSUPPORTED_ARCHS = comcerto2k

MAINTAINER = hgy59
DESCRIPTION = Ghostscript is an interpreter for the PostScript® language and PDF files.
DISPLAY_NAME = ghostscript
CHANGELOG = "Initial package release."

HOMEPAGE = https://ghostscript.com
LICENSE  = AGPL 3.0

STARTABLE = false

# binaries:
FPK_COMMANDS  = bin/gs
FPK_COMMANDS += bin/gxps
FPK_COMMANDS += bin/gpcl6
# scripts:
FPK_COMMANDS += bin/dvipdf
FPK_COMMANDS += bin/eps2eps
FPK_COMMANDS += bin/gsbj
FPK_COMMANDS += bin/gsdj
FPK_COMMANDS += bin/gsdj500
FPK_COMMANDS += bin/gslj
FPK_COMMANDS += bin/gslp
FPK_COMMANDS += bin/gsnd
FPK_COMMANDS += bin/lprsetup.sh
FPK_COMMANDS += bin/pdf2ps
FPK_COMMANDS += bin/pf2afm
FPK_COMMANDS += bin/pfbtopfa
FPK_COMMANDS += bin/pphs
FPK_COMMANDS += bin/printafm
FPK_COMMANDS += bin/ps2ascii
FPK_COMMANDS += bin/ps2epsi
FPK_COMMANDS += bin/ps2pdf
FPK_COMMANDS += bin/ps2pdf12
FPK_COMMANDS += bin/ps2pdf13
FPK_COMMANDS += bin/ps2pdf14
FPK_COMMANDS += bin/ps2pdfwr
FPK_COMMANDS += bin/ps2ps
FPK_COMMANDS += bin/ps2ps2
FPK_COMMANDS += bin/unix-lpr.sh

include ../../mk/fpksrc.fpk.mk
