FPK_NAME = xz
FPK_VERS = 5.6.3
SPK_REV = 1

DEPENDS = cross/xz

MAINTAINER = FnOScommunity
DESCRIPTION = Free general-purpose data compression software with high compression ratio.
DISPLAY_NAME = xz
STARTABLE = false

HOMEPAGE = https://tukaani.org
LICENSE  = various

SPK_COMMANDS = bin/xz bin/xzcat bin/xzdec bin/lzcat bin/unxz bin/lzma bin/lzmadec bin/lzmainfo bin/unlzma

include ../../mk/fpksrc.fpk.mk
