SPK_NAME = lsof
SPK_VERS = 4.99.5
SPK_REV = 1

DEPENDS = cross/lsof

MAINTAINER = FnOScommunity
DESCRIPTION = lsof is a command listing open files.
STARTABLE = false

HOMEPAGE = https://lsof.readthedocs.io/
LICENSE  = https://github.com/lsof-org/lsof/blob/master/COPYING

SPK_COMMANDS = bin/lsof

include ../../mk/fpksrc.fpk.mk
