FPK_NAME = ser2net
FPK_VERS = 4.6.5
FPK_REV = 1
SPK_ICON = src/ser2net.png

DEPENDS = cross/ser2net

# qoriq is the only PPC arch that is supported
UNSUPPORTED_ARCHS = $(OLD_PPC_ARCHS)

MAINTAINER = FnOScommunity
DESCRIPTION = ser2net provides a way for a user to connect from a network connection to a serial port.
DISPLAY_NAME = ser2net
STARTABLE = false

HOMEPAGE = http://ser2net.sourceforge.net/
LICENSE = GPLv2

SPK_COMMANDS = sbin/ser2net

include ../../mk/fpksrc.fpk.mk
