FPK_NAME = htop
FPK_VERS = 3.4.1
FPK_REV = 1
FPK_ICON = src/htop.png

DEPENDS = cross/htop

MAINTAINER = hgy59
DESCRIPTION = Interactive text-mode process viewer for Unix systems. The package is intended for DSM 5.0 or earlier where it\'s not available.
DISPLAY_NAME = htop
STARTABLE = false

HOMEPAGE = http://hisham.hm/htop/
LICENSE = GPLv2+

SPK_COMMANDS = bin/htop

include ../../mk/fpksrc.fpk.mk
