FPK_NAME = jupp
FPK_VERS = 40
FPK_REV = 2
SPK_ICON = src/jupp.png

DEPENDS = cross/jupp

MAINTAINER = FnOScommunity
DESCRIPTION = text editor jupp comes with the editor flavours known from joe, specifically, jmacs, joe, jpico, jstar, and rjoe.
DESCRIPTION_GER = jupp ist ein Editor mit den joe Benutzeroberflächen für emacs, joe, pico, Wordstar und jupp-Benutzeroberfläche.

DISPLAY_NAME = jupp
STARTABLE = false
CHANGELOG = "Update to joe 3.1, jupp v40."

HOMEPAGE = http://www.mirbsd.org/jupp.htm
LICENSE = GPLv1

SPK_COMMANDS = bin/jmacs bin/joe bin/jpico bin/jstar bin/jupp bin/rjoe

include ../../mk/fpksrc.fpk.mk
