FPK_NAME = rmlint
FPK_VERS = 2.10.3
FPK_REV = 1
FPK_ICON = src/rmlint-logo.png

DEPENDS = cross/rmlint

MAINTAINER = FnOScommunity
DESCRIPTION = rmlint finds space waste and other broken things on your filesystem and offers to remove it.
STARTABLE = false

HOMEPAGE = https://github.com/sahib/rmlint
LICENSE = GPLv3

FPK_COMMANDS = bin/rmlint

include ../../mk/fpksrc.fpk.mk
