SPK_NAME = rmlint
SPK_VERS = 2.10.3
SPK_REV = 1
SPK_ICON = src/rmlint-logo.png

DEPENDS = cross/rmlint

MAINTAINER = FnOScommunity
DESCRIPTION = rmlint finds space waste and other broken things on your filesystem and offers to remove it.
STARTABLE = false

HOMEPAGE = https://github.com/sahib/rmlint
LICENSE = GPLv3

SPK_COMMANDS = bin/rmlint

include ../../mk/fpksrc.fpk.mk
