FPK_NAME = njmon
FPK_VERS = 90
FPK_REV = 1

DEPENDS = cross/njmon

MAINTAINER = FnOScommunity
DESCRIPTION = nmon \(Nigel\'s performance Monitor\) is a performance monitoring tool for Linux. njmon outputs JSON format that a lot of tools use these days. It integrates well with saving data directly to InfluxDB and graphing with Grafana.
DISPLAY_NAME = njmon
STARTABLE = false

HOMEPAGE = http://nmon.sourceforge.net/
LICENSE = GPLv3

SPK_COMMANDS = bin/njmon

include ../../mk/fpksrc.fpk.mk
